#! /bin/bash

read -p 'Enter Number: ' n
check=0

for ((i=2; i<=$n/2; i++))
do
	if [ $((n%i)) -eq 0 ]
	then
	echo "Number is not Prime."
		check=1
		break
	fi
done

if [ $check -eq 0 ]
then 
	echo "Number is Prime."
fi 
